name: Publish to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2.1.0
       with:
         fetch-depth: 2
    -  name: Deploy
       uses: SamKirkland/FTP-Deploy-Action@3.1.1
       with:
         ftp-server: ${{ secrets.FTP_HOST }}
         ftp-username: ${{ secrets.FTP_USER }}
         ftp-password: ${{ secrets.FTP_PASSWORD }}
